2025-07-20 04:42:27,058 INFO    MainThread:230407 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /workspace/pytorch_bootcamp/wandb/offline-run-20250720_044227-cyhmqdy1/logs/debug.log
2025-07-20 04:42:27,058 INFO    MainThread:230407 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /workspace/pytorch_bootcamp/wandb/offline-run-20250720_044227-cyhmqdy1/logs/debug-internal.log
2025-07-20 04:42:27,058 INFO    MainThread:230407 [wandb_init.py:init():830] calling init triggers
2025-07-20 04:42:27,058 INFO    MainThread:230407 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-07-20 04:42:27,058 INFO    MainThread:230407 [wandb_init.py:init():871] starting backend
2025-07-20 04:42:27,058 INFO    MainThread:230407 [wandb_init.py:init():874] sending inform_init request
2025-07-20 04:42:27,059 INFO    MainThread:230407 [wandb_init.py:init():882] backend started and connected
2025-07-20 04:42:27,060 INFO    MainThread:230407 [wandb_run.py:_label_probe_notebook():1304] probe notebook
2025-07-20 04:42:27,063 INFO    MainThread:230407 [wandb_init.py:init():953] updated telemetry
2025-07-20 04:42:27,069 INFO    MainThread:230407 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-07-20 04:42:27,115 INFO    MainThread:230407 [wandb_init.py:init():1029] starting run threads in backend
2025-07-20 04:42:27,190 INFO    MainThread:230407 [wandb_run.py:_console_start():2458] atexit reg
2025-07-20 04:42:27,190 INFO    MainThread:230407 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-07-20 04:42:27,190 INFO    MainThread:230407 [wandb_run.py:_redirect():2375] Wrapping output streams.
2025-07-20 04:42:27,190 INFO    MainThread:230407 [wandb_run.py:_redirect():2398] Redirects installed.
2025-07-20 04:42:27,191 INFO    MainThread:230407 [wandb_init.py:init():1075] run started, returning control to user process
2025-07-20 04:42:58,502 INFO    MainThread:230407 [wandb_run.py:_config_callback():1363] config_cb None None {'learning_rate': 0.001, 'batch_size': 32, 'epochs': 10, 'model_type': 'SafeLayerDeviceController', 'experiment': 'device_control_timing'}
2025-07-20 04:46:34,962 WARNING MsgRouterThr:230407 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/root/miniconda3/envs/good/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/root/miniconda3/envs/good/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 231, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/root/miniconda3/envs/good/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 216, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/good/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/root/miniconda3/envs/good/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-07-20 04:46:34,963 INFO    MsgRouterThr:230407 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 0 handles.
